# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: benchmark

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - "*"
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - id: install-xvfb
        run: |
          sudo apt-get install xvfb

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn --immutable

      - id: yarn-cache-dir-path-benchmark
        working-directory: ./benchmarks
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache-benchmark # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path-benchmark.outputs.dir }}
          key: ${{ runner.os }}-benchmark-yarn-${{ hashFiles('./benchmarks/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-benchmark-yarn-

      - working-directory: ./benchmarks
        run: yarn --immutable

      - working-directory: ./benchmarks
        run: yarn build

      - working-directory: ./benchmarks
        run: xvfb-run --auto-servernum yarn benchmark

      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          path: ./benchmarks/results.json
